const AUDIT_ACTIONS = {
  LOGIN_SUCCESS:
    'LOGIN_SUCCESS',

  LOGIN_FAILED:
    'LOGIN_FAILED',

  LOGOUT:
    'LOGOUT',

  SESSION_CREATED:
    'SESSION_CREATED',

  SESSION_REVOKED:
    'SESSION_REVOKED',

  USER_DISABLED:
    'USER_DISABLED',

  USER_ENABLED:
    'USER_ENABLED',

  USER_SESSIONS_REVOKED:
    'USER_SESSIONS_REVOKED',

  FEATURE_ENABLED:
    'FEATURE_ENABLED',

  FEATURE_DISABLED:
    'FEATURE_DISABLED',

  NOTIFICATION_PUBLISHED:
    'NOTIFICATION_PUBLISHED',

  NOTIFICATION_DISABLED:
    'NOTIFICATION_DISABLED',

  API_KEY_CREATED:
    'API_KEY_CREATED',

  API_KEY_REVOKED:
    'API_KEY_REVOKED',

  BACKUP_CREATED:
    'BACKUP_CREATED',

  DEPLOYMENT_STARTED:
    'DEPLOYMENT_STARTED',
};

module.exports =
  AUDIT_ACTIONS;
